import { db } from '@/lib/db';
import DashboardLayout from '@/components/layout/DashboardLayout';
import StatCard from '@/components/ui/StatCard'; import StatusBadge from '@/components/ui/StatusBadge';
import { useEffect,useMemo,useState } from 'react'; import { supabase } from '@/integrations/supabase/client';
import { Briefcase,Building2,GraduationCap,Globe2,Search,MapPin } from 'lucide-react';
import { Input } from '@/components/ui/input';
export default function CareerMarketplace(){const [ops,setOps]=useState<any[]>([]),[apps,setApps]=useState<any[]>([]),[q,setQ]=useState('');
 useEffect(()=>{Promise.all([db.from('career_opportunities').select('*,career_organisations(name,verified)').eq('status','open').order('created_at',{ascending:false}),db.from('career_applications').select('*')]).then(([o,a])=>{setOps(o.data||[]);setApps(a.data||[])})},[]);
 const filtered=useMemo(()=>ops.filter(o=>(o.title+' '+o.country+' '+(o.city||'')+' '+(o.career_organisations?.name||'')).toLowerCase().includes(q.toLowerCase())),[ops,q]);
 return <DashboardLayout title="Careers & Internships" subtitle="Verified opportunities, applications and international careers">
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5"><StatCard label="Open Opportunities" value={ops.length} icon={Briefcase}/><StatCard label="Internships" value={ops.filter(o=>o.opportunity_type==='internship').length} icon={GraduationCap}/><StatCard label="Sponsorship Listed" value={ops.filter(o=>o.sponsorship_available).length} icon={Globe2}/><StatCard label="My Applications" value={apps.length} icon={Building2}/></div>
 <div className="relative max-w-xl mb-4"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search internships, jobs, city or employer…" value={q} onChange={e=>setQ(e.target.value)}/></div>
 <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(o=><div key={o.id} className="surface-card p-5 hover-lift"><div className="flex items-start justify-between gap-2"><div><p className="text-label">{o.opportunity_type.replace(/_/g,' ')}</p><h3 className="font-bold mt-1">{o.title}</h3><p className="text-xs text-muted-foreground mt-1">{o.career_organisations?.name||'Verified partner'}</p></div>{o.career_organisations?.verified&&<StatusBadge status="Verified" variant="success"/>}</div><p className="text-xs mt-4 flex items-center gap-1"><MapPin className="w-3.5 h-3.5"/>{o.city?o.city+', ':''}{o.country}{o.remote?' · Remote':''}</p><div className="flex gap-2 mt-4">{o.sponsorship_available&&<StatusBadge status="Sponsorship information available" variant="info"/>}<StatusBadge status={o.status}/></div><p className="text-[11px] text-muted-foreground mt-3">Sponsorship information does not guarantee visa eligibility.</p></div>)}</div>
 </DashboardLayout>}