-- Seed launch readiness catalogue. Everything starts pending/not configured; evidence is required to turn green.
insert into public.production_integrations(tenant_id,integration_key,category,required_for_launch,status)
select t.id,x.k,x.c,x.r,'not_configured' from public.tenants t cross join (values
 ('microsoft_entra_graph','identity_teaching',true),('institutional_email','communications',true),('payment_gateway','payments',true),('bank_mobile_wallet','payments',false),('stemcoach_sso','learning',true),('stemcoach_progress_sync','learning',true),('nadra_identity','identity',false),('turnitin_similarity','academic_integrity',false),('virtual_lab_provider','practical_learning',false),('sms_whatsapp','communications',false),('physical_access_control','campus_security',false),('cctv_vms','campus_security',false),('apple_app_store','native',false),('google_play','native',false),('omniqora_central_factory','platform',false)
) as x(k,c,r) on conflict(tenant_id,integration_key) do nothing;
insert into public.production_readiness_checks(tenant_id,check_key,category,status)
select t.id,x.k,x.c,'pending' from public.tenants t cross join (values
 ('ci_main_green','code'),('migration_replay_clean','database'),('generated_types_current','database'),('rls_cross_tenant_negative_tests','security'),('private_storage_policy_tests','security'),('edge_function_authz_review','security'),('critical_e2e_personas','quality'),('mobile_responsive_smoke','quality'),('backup_restore_drill','resilience'),('monitoring_alerts_verified','operations'),('load_test_3000_learners','performance'),('live_class_300_workflow','performance'),('launch_course_packs_approved','academic'),('awarding_body_claims_verified','academic'),('marker_iqa_capacity','academic'),('safeguarding_policies_approved','operations'),('residential_sop_verified','operations'),('placement_partners_verified','operations'),('exam_controls_verified','academic'),('pilot_cohort_complete','launch')
) as x(k,c) on conflict(tenant_id,check_key) do nothing;
